// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-tickets.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_tickets_default = defineTool({
  name: "list_my_tickets",
  title: "List my tickets",
  description: "List helpdesk tickets visible to the signed-in user (respects RLS). Filter by status and limit results.",
  inputSchema: {
    status: z.string().optional().describe("Optional exact status filter, e.g. 'Aberto', 'Em Andamento', 'Resolvido'."),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("tickets").select("id,title,status,priority,type,sector,created_at,due_date,assigned_to,created_by").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-ticket.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_ticket_default = defineTool2({
  name: "get_ticket",
  title: "Get ticket",
  description: "Fetch a single helpdesk ticket by ID, including its public comments. RLS applies.",
  inputSchema: {
    ticket_id: z2.string().uuid().describe("Ticket UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const [{ data: ticket, error: tErr }, { data: comments, error: cErr }] = await Promise.all([
      sb.from("tickets").select("*").eq("id", ticket_id).maybeSingle(),
      sb.from("ticket_comments").select("id,message,created_at,author_id,is_internal").eq("ticket_id", ticket_id).order("created_at", { ascending: true })
    ]);
    if (tErr) return { content: [{ type: "text", text: tErr.message }], isError: true };
    if (!ticket) return { content: [{ type: "text", text: "Ticket not found" }], isError: true };
    const payload = { ticket, comments: cErr ? [] : comments ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-ticket.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_ticket_default = defineTool3({
  name: "create_ticket",
  title: "Create ticket",
  description: "Create a new helpdesk ticket on behalf of the signed-in user. The user's organization is auto-assigned by the database.",
  inputSchema: {
    title: z3.string().trim().min(3).describe("Short ticket title."),
    description: z3.string().trim().optional().describe("Full description of the issue."),
    priority: z3.enum(["Baixa", "M\xE9dia", "Alta", "Urgente"]).default("M\xE9dia").describe("Ticket priority."),
    type: z3.string().trim().optional().describe("Ticket type/category label, e.g. 'Hardware'."),
    sector: z3.string().trim().optional().describe("Sector/department the ticket belongs to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, priority, type, sector }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const userId = ctx.getUserId();
    const { data: pending, error: pendingErr } = await sb.from("tickets").select("id, title, aguardando_aprovacao_at").eq("created_by", userId).eq("status", "Aguardando Aprova\xE7\xE3o");
    if (pendingErr) {
      return { content: [{ type: "text", text: pendingErr.message }], isError: true };
    }
    if (pending && pending.length > 0) {
      const list = pending.map((p) => `- ${p.id} \u2014 ${p.title}`).join("\n");
      return {
        content: [
          {
            type: "text",
            text: `Cannot open a new ticket: you have ${pending.length} ticket(s) awaiting approval. Approve or send them back for rework before opening another.

${list}`
          }
        ],
        structuredContent: { error: "pending_approval_tickets", pending },
        isError: true
      };
    }
    const { data, error } = await sb.from("tickets").insert({
      title,
      description: description ?? null,
      priority,
      type: type ?? "Outros",
      sector: sector ?? null,
      status: "Aberto",
      created_by: userId
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { ticket: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gtimcognsszzsfpavups";
var mcp_default = defineMcp({
  name: "grti-helpdesk-mcp",
  title: "GRTI Helpdesk",
  version: "0.1.0",
  instructions: "Tools for the GRTI Helpdesk. Use `list_my_tickets` to browse tickets visible to the signed-in user, `get_ticket` to read a single ticket with its comments, and `create_ticket` to open a new ticket. All access is scoped to the signed-in user via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_tickets_default, get_ticket_default, create_ticket_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
